version = 0.1

[default.deploy.parameters]
stack_name = "tripcharge"
resolve_s3 = true
s3_prefix = "tripcharge"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "us-west-1"
